language: cpp
os: linux
dist: xenial
services: docker

jobs:
  include:
    - env: DOCKERFILE="debian-bullseye"
    - env: DOCKERFILE="ubuntu-jammy"
      dist: focal # Need a newer docker host for Jammy guest
    - env: DOCKERFILE="ubuntu-focal"

install:
  - if [ -n "$DOCKERFILE" ]; then
      ./script/docker-build.sh "$DOCKERFILE";
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
       brew update;
       brew tap homebrew/science;
       brew install autoconf-archive openblas maxima sdl2 libtool ompl;
       brew install https://raw.github.com/dartsim/homebrew-dart/master/Formula/fcl.rb;
    fi

script:
  - if [ -n "$DOCKERFILE" ]; then
      ./script/docker-make.sh "$DOCKERFILE";
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      autoreconf -i &&
      ./configure &&
      make -k -j $JOBS &&
      make check;
    fi

branches:
  only:
    - master
    - main
    - /^feature\/.*/
    - /^bugfix\/.*/


## PRIOR CONFIGS
#
# jobs:
#   include:
#     - os: linux
#       sudo: required
#       services:
#         - docker
#       env: DOCKERFILE="debian-stretch" JOBS=4
#     - os: linux
#       sudo: required
#       services:
#         - docker
#       env: DOCKERFILE="ubuntu-xenial" JOBS=4
#     - os: linux
#       sudo: required
#       services:
#         - docker
#       env: DOCKERFILE="ubuntu-bionic" JOBS=4
#     - os: linux
#       sudo: required
#       services:
#         - docker
#       env: DOCKERFILE="debian-sid" JOBS=4
#     - os: linux
#       sudo: required
#       services:
#         - docker
#       env: DOCKERFILE="debian-jessie" JOBS=4
#     - os: linux
#       sudo: required
#       services:
#         - docker
#       env: DOCKERFILE="ubuntu-trusty" JOBS=4
#     - os: osx
#       compiler: clang
#       env: CPPFLAGS=-I/usr/local/opt/openblas/include JOBS=2
#       cache:
#         directories:
#           - /usr/local
#     - os: linux
#       dist: trusty
#       sudo: required
#       compiler: gcc
#       env: JOBS=4

# notifications:
#   slack:
#     secure: UsjxGKXWmNW+6nt0ZDwU3MOEFXf69Paj8gYUpTB/DLrgC9d7LtzvYYmSDitc6XFMVB3RjodhIcD3+Kayz8+SFu/fsRBPqwT19B7e0ThmGY/DHr1xN8A3s/OmHAK+Pybvj3DEUDHhoiqUzKftlxHpUhRXJyxBo9r+CYb+XDnJfQs=

#cache:
  #apt: true
  #directories:
    #- /usr/local

#before_install:
  #- sudo docker pull ubuntu:xenial
  #- docker ps -a

# addons:
#   apt:
#     packages:
#       - libboost-all-dev
#       - gfortran
#       - automake
#       - autoconf
#       - autoconf-archive
#       - autotools-dev
#       - libblas-dev
#       - liblapack-dev
#       - libsdl2-dev
#       - libompl-dev
#       - coinor-libclp-dev
#       - libglpk-dev
#       - libav-tools
#       - doxygen
#       - groff
